theme: minima
title: My First GitHub Page
author: Matthew Harrison
email: m_w_h@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Just a simple lil' learner site. I can edit this
  line in _config.yml. It will appear in my document head meta (for
  Google search results) and in my feed.xml site description.

# social links
twitter_username: mattharrisonnn # DO NOT include the @ character, or else the build will fail!
github_username:  mattharrisonn # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
